Added special option to define backup prefix.

diff --git a/src/bash/purge-backups b/src/bash/purge-backups
--- a/src/bash/purge-backups
+++ b/src/bash/purge-backups
@@ -28,12 +28,13 @@ function convertToSeconds {
 # Function that prints the help message
 printHelp() {
   cat <<EOF
-Usage: $0 [-h] [-p backup-path] [-d daily-retention] [-w weekly-retention] [-m monthly-retention] [-y yearly-retention]
+Usage: $0 [-h] [-p backup-path] [-x backup-prefix] [-d daily-retention] [-w weekly-retention] [-m monthly-retention] [-y yearly-retention]
 
 Deletes old backup directories according to the specified retention policies.
 
 Required arguments:
   -p|--backup-path <path>        Parent directory of backup directories to be cleaned.
+  -x|--backup-prefix <prefix>    Prefix of the backed up entity (e.g., my_backup).
 
 Optional arguments:
   -d|--daily-retention <num>    Number of days to keep daily backups (default: $dailyRetention day(s)).
@@ -56,13 +57,13 @@ Backup directory name format:
 
 Examples:
   # Retention policy: keep daily backups for 30 days
-  $0 -p /backups/mybackup -d 30d
+  $0 -p /backups/mybackup -x my_backup -d 30d
 
   # Retention policy: keep monthly backups for 6 months and weekly backups for 4 weeks, and daily backups for 3 days
-  $0 -p /backups/mybackup -m 6M -w 4W -d 3D
+  $0 -p /backups/mybackup -x my_backup -m 6M -w 4W -d 3D
 
   # Perform a dry run to print the directories that would be deleted without actually deleting them
-  $0 -p /backups/mybackup --dry-run
+  $0 -p /backups/mybackup -x my_backup --dry-run
 EOF
 }
 
@@ -78,6 +79,10 @@ while [[ $# -gt 0 ]]; do
   case "$1" in
     -p|--backup-path)
       backupPath="$2"
+      shift
+      ;;
+    -x|--backup-prefix)
+      backupPrefix="$2"
       shift
       ;;
     -d|--daily-retention)
@@ -119,6 +124,13 @@ if [ -z "$backupPath" ]; then
   exit 1
 fi
 
+# Check if backup prefix is provided
+if [ -z "$backupPrefix" ]; then
+  echo "Backup prefix is required. Please provide a value for the -x or --backup-prefix option."
+  printHelp
+  exit 1
+fi
+
 # Calculate retention time in seconds
 dailyRetentionSeconds=$(convertToSeconds "${dailyRetention%${dailyRetention##*[!0-9]}}" "${dailyRetention##*[0-9]}")
 weeklyRetentionSeconds=$(convertToSeconds "${weeklyRetention%${weeklyRetention##*[!0-9]}}" "${weeklyRetention##*[0-9]}")
@@ -134,7 +146,7 @@ fi
 for dir in "${backupPath}"/*; do
   if [[ -d "${dir}" ]]; then
     # Get the backup date from the directory name
-    backupDate=$(basename "${dir}" | cut -d'_' -f2)
+    backupDate=$(echo "${dir#$backupPrefix'_'}" | cut -d'_' -f1)
 
     # Convert the backup date to Unix timestamp
     backupTimestamp=$(date -d "${backupDate}" +%s)
